import struct LiaSupport.Syntax
import struct TemplateDescription.Template
import struct LiaDescription.TemplateBundle
import enum LiaDescription.IdentifierConversionMethod
import enum LiaDescription.UnknownFileMethod

public typealias LocatedSyntaxDescription = LiaSupport.Syntax
public typealias LocatedTemplateDescription = TemplateDescription.Template
public typealias LocatedTemplateBundleDescription = LiaDescription.TemplateBundle

public typealias LocatedIdentifierConversionMethod = LiaDescription.IdentifierConversionMethod
public typealias LocatedUnknownFileMethod = LiaDescription.UnknownFileMethod
